[project]
name = 'Specialized-Medical-Equipment-Sharing'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.equipment-registry]
path = 'contracts/equipment-registry.clar'
clarity_version = 2
epoch = 2.5

[contracts.sanitization-verification]
path = 'contracts/sanitization-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.training-verification]
path = 'contracts/training-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
